name: Generate AI TTS Video with Subtitles

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir numpy
          pip install --no-cache-dir imageio imageio[ffmpeg]  # Required for MoviePy
          pip install --no-cache-dir moviepy  # Install MoviePy separately
          pip install --no-cache-dir elevenlabs whisper ffmpeg-python pysrt

      - name: Run Python Script to Generate Video
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        run: python generate_video.py

      - name: Upload Final Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: youtube_short_with_subtitles
          path: youtube_short_with_big_subtitles.mp4
