name: Generate AI TTS Video with Subtitles

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Debug Python Environment
        run: |
          python -V
          python -m site
          which python
          pip -V
          pip list

      - name: Install Dependencies Step 1 (Base Packages)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir numpy pandas

      - name: Install Dependencies Step 2 (MoviePy & FFmpeg)
        run: |
          pip install --no-cache-dir imageio imageio[ffmpeg]  # Required for MoviePy
          pip install --no-cache-dir moviepy  # Install MoviePy separately
          pip install --no-cache-dir opencv-python-headless

      - name: Verify MoviePy Installation
        run: |
          python -c "import moviepy.editor as mp; print('✅ MoviePy is installed successfully!')"

      - name: Install Dependencies Step 3 (Other Required Libraries)
        run: |
          pip install --no-cache-dir elevenlabs whisper ffmpeg-python pysrt

      - name: Run Python Script to Generate Video
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        run: python generate_video.py

      - name: Upload Final Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: youtube_short_with_subtitles
          path: youtube_short_with_big_subtitles.mp4
