name: Generate AI TTS Video with Subtitles

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Debug Python Environment
        run: |
          echo "🐍 Python Version:"
          python -V
          echo "📂 Python Path:"
          which python
          echo "📦 Installed Packages (Before Install):"
          pip list

      - name: Remove Existing MoviePy Installation (If Any)
        run: |
          pip uninstall -y moviepy

      - name: Force Install MoviePy and Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --force-reinstall --no-cache-dir numpy pandas
          pip install --force-reinstall --no-cache-dir imageio imageio[ffmpeg]
          pip install --force-reinstall --no-cache-dir opencv-python-headless
          pip install --force-reinstall --no-cache-dir moviepy

      - name: Verify MoviePy Installation
        run: |
          python -c "import moviepy.editor as mp; print('✅ MoviePy is installed successfully!')"

      - name: Install Other Required Libraries
        run: |
          pip install --force-reinstall --no-cache-dir elevenlabs whisper ffmpeg-python pysrt

      - name: Debug Python Environment (After Install)
        run: |
          echo "📦 Installed Packages (After Install):"
          pip list

      - name: Check MoviePy Location
        run: |
          python -c "import moviepy; print(moviepy.__file__)"

      - name: Run Python Script to Generate Video
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        run: python generate_video.py

      - name: Upload Final Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: youtube_short_with_subtitles
          path: youtube_short_with_big_subtitles.mp4
